db:
  db_name: "honeypot_db"
  host: "10.211.55.4"
  port: 3306
  user: "root"
  password: "123456"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 10000
logger:
  format: json
  appName: image_server
  level: info
redis:
  addr: 10.211.55.4:6379
  password:
  db: 1
system:
  mode: release # debug
  webAddr: ":8080" # web的运行地址
#  grpcAddr: ":8081"
jwt:
  expires: 8640000
  issuer: reisen
  secret: kfcvme50
whiteList:
  - /honeypot_server/login
  - /honeypot_server/captcha
  - /honeypot_server/site
  - /honeypot_server/register
vsNet:
  name: honeypot-hp
  prefix: hp-
  net: 10.2.1.0/24